"""Golden end-to-end submitted-cell regressions for magnetic structures."""

import io
from pathlib import Path
import sys

import numpy as np
import pytest
from ase.build import make_supercell
from ase.io import read
from ase.io import write

from alterseek.kpoints import KPathBuilder, OUTPUT_DIR


REFERENCES = Path(__file__).parent / "references"
SUPERCELL_211 = REFERENCES / "SUPERCELL_211.vasp"
SUPERCELL_221 = REFERENCES / "SUPERCELL_221.vasp"
CHANGED_CELL_AM = REFERENCES / "case15_changed_cell_altermagnet.vasp"
BIFEO3_PRIMITIVE = REFERENCES / "BiFeO3_R3c_primitive.vasp"


def _mapping_matrix(path, key):
    lines = path.read_text(encoding="utf-8").splitlines()
    start = lines.index(f"{key}:") + 1
    return np.array([
        [float(value) for value in line.split()]
        for line in lines[start:start + 3]
    ])


def _kpoint_rows(path):
    rows = []
    for line in path.read_text(encoding="utf-8").splitlines()[4:]:
        fields = line.split()
        if len(fields) >= 4:
            try:
                coords = [float(value) for value in fields[:3]]
            except ValueError:
                continue
            rows.append((*coords, fields[3]))
    return rows


def _run(monkeypatch, tmp_path, structure, moments, *, operation=None):
    answers = [str(structure), "0 0 1", moments, ""]
    if operation is not None:
        answers.append(operation)
    answers.append("")
    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(sys, "stdin", io.StringIO("\n".join(answers) + "\n"))
    assert KPathBuilder().interactive_build() is True
    return tmp_path / OUTPUT_DIR


def _assert_submitted_output_contract(tmp_path, output_dir, structure):
    stem = structure.stem
    submitted = np.asarray(read(structure).cell, dtype=float)
    mapping = output_dir / f"{stem}_seekpath_basis_mapping.txt"

    assert np.allclose(
        _mapping_matrix(mapping, "analysis_input_lattice"), submitted
    )
    assert np.allclose(
        _mapping_matrix(mapping, "kpoints_output_lattice"), submitted
    )
    assert (output_dir / f"{stem}_magnetic_primitive.mcif").exists()
    assert not (output_dir / f"{stem}_seekpath_marker_helper.vasp").exists()
    assert not (output_dir / f"{stem}_seekpath_standard.vasp").exists()
    assert not (tmp_path / f"{stem}_magnetic_primitive.vasp").exists()
    assert not (tmp_path / f"{stem}_magnetic_primitive_MAGMOM.txt").exists()


def test_determinant_one_211_basis_is_the_native_output_cell(
    tmp_path, monkeypatch, capsys
):
    output_dir = _run(
        monkeypatch,
        tmp_path,
        SUPERCELL_211,
        "1 -1 1 -1",
    )
    stdout = capsys.readouterr().out
    kpoints = tmp_path / "KPOINTS_alter"
    text = kpoints.read_text(encoding="utf-8")

    assert "Magnetic primitive cell:      SG Cmc2_1 (36)" in stdout
    magnetic_row = next(
        row for row in stdout.splitlines()
        if row.startswith("Magnetic primitive cell:")
    )
    assert "[12 atoms, oC1]" in magnetic_row
    assert "Input cell:                   SG Cmc2_1 (36)" in stdout
    assert "Conventional/supercell detected:" not in stdout
    assert "Conventional/supercell BZ:" not in stdout
    assert "Pmm2" not in stdout
    assert "SG SG" not in stdout
    assert "[12 atoms, oC1]" in stdout
    assert (
        stdout.index("Input cell:")
        < stdout.index("Nonmagnetic primitive cell:")
        < stdout.index("Magnetic primitive cell:")
    )
    assert text.startswith("K-Path generated by AlterSeeK-Path (HPKOT oC1)")
    labels = {row[3] for row in _kpoint_rows(kpoints)}
    assert {"GAMMA", "Y", "T", "Z", "S", "R"} <= labels
    _assert_submitted_output_contract(
        tmp_path, output_dir, SUPERCELL_211
    )


def test_true_221_supercell_gets_native_hexagonal_labels_and_basis(
    tmp_path, monkeypatch, capsys
):
    output_dir = _run(
        monkeypatch,
        tmp_path,
        SUPERCELL_221,
        "4*8 4*-8 16*0",
        operation="1",
    )
    stdout = capsys.readouterr().out
    kpoints = tmp_path / "KPOINTS_alter"
    rows = _kpoint_rows(kpoints)

    assert "Input cell:                   SG P6_3mc (186)" in stdout
    assert "Conventional/supercell BZ:    hP2" in stdout
    assert "P6mm" not in stdout
    assert "[24 atoms, hP2]" in stdout
    assert (
        stdout.index("Input cell:")
        < stdout.index("Nonmagnetic primitive cell:")
        < stdout.index("Magnetic primitive cell:")
        < stdout.index("Conventional/supercell BZ:")
    )
    assert "GAMMA-M-K-GAMMA-A-L-H-A" in stdout
    assert kpoints.read_text(encoding="utf-8").startswith(
        "Selected spin-flip operation (Option 1) in submitted structure "
        "'SUPERCELL_221.vasp'"
    )
    assert any(
        label.rstrip("'") == "K"
        and np.allclose(coords, [1 / 3, 1 / 3, 0.0], atol=1e-8)
        for *coords, label in rows
    )
    _assert_submitted_output_contract(
        tmp_path, output_dir, SUPERCELL_221
    )


def test_no_moments_reports_the_same_cell_summary_without_magnetic_row(
    tmp_path, monkeypatch, capsys
):
    _run(monkeypatch, tmp_path, SUPERCELL_221, "")
    stdout = capsys.readouterr().out

    assert "Input structure: SUPERCELL_221.vasp, 24 atoms" in stdout
    assert (
        "Conventional/supercell detected: input contains 4 nonmagnetic "
        "primitive cells"
    ) in stdout
    assert "Input cell:                   SG P6_3mc (186)" in stdout
    assert "Nonmagnetic primitive cell:   SG P6_3mc (186)" in stdout
    assert "Magnetic primitive cell:" not in stdout
    assert "Conventional/supercell BZ:    hP2" in stdout
    assert "Lattice type:" not in stdout


def test_same_volume_case15_never_replaces_the_calculation_cell(
    tmp_path, monkeypatch, capsys
):
    output_dir = _run(
        monkeypatch,
        tmp_path,
        CHANGED_CELL_AM,
        "0 2*1 2*-1 8*0",
        operation="",
    )
    stdout = capsys.readouterr().out
    kpoints_text = (tmp_path / "KPOINTS_alter").read_text(encoding="utf-8")

    assert "Magnetic primitive cell:" in stdout
    assert "SG Immm (71)" in stdout
    assert "Input cell:" in stdout
    assert "Conventional/supercell BZ:" not in stdout
    assert "Phase: AFM(Altermagnet)" in stdout
    assert "11 original segments -> 28 generated segments" in stdout
    assert "in submitted structure 'case15_changed_cell_altermagnet.vasp'" \
        in kpoints_text.splitlines()[0]
    _assert_submitted_output_contract(
        tmp_path, output_dir, CHANGED_CELL_AM
    )


def test_211_converts_seekpath_points_to_submitted_basis_preserving_cartesian(
    tmp_path, monkeypatch
):
    output_dir = _run(
        monkeypatch,
        tmp_path,
        SUPERCELL_211,
        "1 -1 1 -1",
    )
    mapping = output_dir / "SUPERCELL_211_seekpath_basis_mapping.txt"
    submitted = _mapping_matrix(mapping, "kpoints_output_lattice")
    primitive = _mapping_matrix(
        mapping, "seekpath_standard_primitive_lattice"
    )
    rotation = _mapping_matrix(mapping, "seekpath_rotation_matrix")
    b_submitted = 2 * np.pi * np.linalg.inv(submitted).T
    b_primitive = 2 * np.pi * np.linalg.inv(primitive).T

    # The oC1 helper supplies Y=(-1/2,1/2,0) internally. Its submitted-basis
    # fraction differs, but both fractions represent the same Cartesian point.
    y_rows = [np.array(row[:3]) for row in _kpoint_rows(
        tmp_path / "KPOINTS_alter"
    ) if row[3] == "Y"]
    expected_internal_fraction = np.array([-0.5, 0.5, 0.0])
    expected_output_fraction = np.array([-1.0, 0.0, 0.0])
    assert y_rows
    assert all(np.allclose(row, expected_output_fraction) for row in y_rows)
    standardized_cart = expected_internal_fraction @ b_primitive @ rotation
    for row in y_rows:
        assert np.allclose(row @ b_submitted, standardized_cart, atol=1e-8)


def test_bifeo3_hP_helper_preserves_figure_and_output_spin_relations(
    tmp_path, monkeypatch, capsys
):
    primitive = read(BIFEO3_PRIMITIVE)
    primitive.set_initial_magnetic_moments([4.0, -4.0] + [0.0] * 8)
    conventional = make_supercell(
        primitive,
        np.array([
            [1, -1, 0],
            [0, 1, -1],
            [1, 1, 1],
        ]),
        order="cell-major",
        wrap=True,
    )
    species_order = {"Fe": 0, "Bi": 1, "O": 2}
    conventional = conventional[sorted(
        range(len(conventional)),
        key=lambda index: species_order[conventional[index].symbol],
    )]
    structure = tmp_path / "BiFeO3_hexagonal.vasp"
    write(structure, conventional, format="vasp", direct=True, vasp5=True)
    moments = " ".join(
        f"{moment:g}"
        for moment in conventional.get_initial_magnetic_moments()
    )

    captured = {}

    def capture_spin_figures(
        self,
        centroid_result,
        struct_file,
        general_kpoint,
        operation,
        cartesian_operation,
        flip_operations,
        preserve_operations,
        path_points,
        display_figures,
        save_pdf=False,
    ):
        captured["centroid_result"] = centroid_result
        captured["general_kpoint"] = np.asarray(general_kpoint, dtype=float)
        captured["operation"] = np.asarray(operation, dtype=float)
        captured["path_points"] = path_points
        self._validate_standardized_spin_map(
            centroid_result, operation, cartesian_operation
        )

    monkeypatch.setattr(
        KPathBuilder,
        "_generate_spin_figures",
        capture_spin_figures,
    )
    _run(
        monkeypatch,
        tmp_path,
        structure,
        moments,
        operation="1",
    )
    stdout = capsys.readouterr().out
    assert (
        "Conventional/supercell detected: input contains 3 magnetic "
        "primitive cells"
    ) in stdout
    assert (
        stdout.index("Input structure:")
        < stdout.index("Conventional/supercell detected:")
        < stdout.index("Input cell:")
    )

    kpoints = tmp_path / "KPOINTS_alter"
    header = kpoints.read_text(encoding="utf-8").splitlines()[0]
    submitted_operation = np.array([
        float(value) for value in header.split("basis:", 1)[1].split()
    ]).reshape(3, 3)
    standardized_operation = captured["operation"]
    assert captured["centroid_result"]["sc_type"] == "hP2"
    assert np.isclose(
        captured["centroid_result"]["ibz_volume"]
        * captured["centroid_result"]["n_symmetry_ops"],
        abs(np.linalg.det(captured["centroid_result"]["b_matrix"])),
        rtol=1e-7,
        atol=1e-10,
    )
    KPathBuilder._validate_standardized_spin_map(
        captured["centroid_result"], standardized_operation
    )

    rows = _kpoint_rows(kpoints)
    output_k = np.array(next(row[:3] for row in rows if row[3] == "k"))
    output_k_prime = np.array(
        next(row[:3] for row in rows if row[3] == "k'")
    )
    assert np.allclose(
        output_k_prime,
        np.linalg.inv(submitted_operation).T @ output_k,
        atol=1e-8,
    )

    figure_k_prime = np.array(next(
        point[:3]
        for point in captured["path_points"]
        if point is not None and point[3] == "k'"
    ))
    assert np.allclose(
        figure_k_prime,
        np.linalg.inv(standardized_operation).T
        @ captured["general_kpoint"],
        atol=1e-8,
    )


def test_bifeo3_conventional_cell_generates_hP_spin_figures(
    tmp_path, monkeypatch
):
    primitive = read(BIFEO3_PRIMITIVE)
    primitive.set_initial_magnetic_moments([4.0, -4.0] + [0.0] * 8)
    conventional = make_supercell(
        primitive,
        np.array([
            [1, -1, 0],
            [0, 1, -1],
            [1, 1, 1],
        ]),
        order="cell-major",
        wrap=True,
    )
    species_order = {"Fe": 0, "Bi": 1, "O": 2}
    conventional = conventional[sorted(
        range(len(conventional)),
        key=lambda index: species_order[conventional[index].symbol],
    )]
    structure = tmp_path / "BiFeO3_hexagonal_full.vasp"
    write(structure, conventional, format="vasp", direct=True, vasp5=True)
    moments = " ".join(
        f"{moment:g}"
        for moment in conventional.get_initial_magnetic_moments()
    )

    output_dir = _run(
        monkeypatch,
        tmp_path,
        structure,
        moments,
        operation="1",
    )

    stem = structure.stem
    for suffix in (
        "ibz_hP2",
        "spinflip_hP2",
        "spinbz_hP2",
        "spinbz_top_hP2",
    ):
        assert (output_dir / f"{stem}_{suffix}.png").exists()
    assert not list(output_dir.glob(f"{stem}_*hR*.png"))
